source_data_list:
  - ADDR
SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id

OL:
  sftp_conf:
    filetype: csv
    delimiter: "|"
    directory: /home/ubuntu/data/
    filename: receipts_delta_GBR_14_10_2017.csv

CP:
  s3_source_conf:
    s3_bucket: chandraaws
    sourcefile: KC_Extract_1_20171009.csv


s3_conf:
  s3_bucket: chandraaws
  staging_dir : staging

ADDR:
mongodb_config:
  database: customer
  collection: address


redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT