source_data_list:
  - CP

target_data_list:
  - REGIS_DIM

s3_conf:
  s3_bucket: chandraaws
  staging_dir : staging

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id

OL:
  sftp_conf:
    filetype: csv
    delimiter: "|"
    directory: /home/ubuntu/data/
    filename: receipts_delta_GBR_14_10_2017.csv

CP:
  s3_source_conf:
    s3_bucket: chandraaws
    sourcefile: KC_Extract_1_20171009.csv


ADDR:
  mongodb_config:
    database: customer
    collection: address


REGIS_DIM:
    tableName: DATAMART.REGIS_DIM
    sourceTable:
      - CP
    loadingQuery: >
            SELECT
               DATAMART.FN_UUID() AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,REGIS_CTY_CODE AS CTY_CODE,
               REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_TS
              FROM
                (SELECT
                   DISTINCT REGIS_CNSM_ID, CAST(REGIS_CTY_CODE AS SMALLINT), CAST(REGIS_ID AS INTEGER),
                   REGIS_LTY_ID, REGIS_DATE, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, INS_TS
                FROM
                  staging_STG_1CP
                WHERE
                  CAST(INS_TS AS DATE) = CURRENT_DATE
                ) CP

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT